/**
 * publish: validate a skin directory, build the `.skin` tar.gz bundle, and
 * submit it to the Clawso marketplace.
 *
 * Mirrors the tool publish flow. The marketplace endpoint
 *   POST ${apiBase}/api/marketplace/skins/submit
 * authenticates with a publisher bearer token and takes multipart/form-data:
 *   - bundle                    the .skin tar.gz (≤5MB)
 *   - admin_review_checklist    markdown
 *   - deployment_verification   markdown
 *   - release_notes             optional text
 *
 * On success the endpoint returns { slug, version, bundle_sha256, state,
 * review_url, estimated_review_time }. `state` is `published-direct` for a
 * permissively-licensed skin, otherwise `pending-review`.
 *
 * Uses Node 20+ globals (fetch, FormData, Blob) — no network dependency is
 * added. The bundle is built in memory and only hits the network on a real run;
 * `--dry-run` does everything except the POST.
 */
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { validateSkin } from "./validate";
import { buildSkinTarball, BundleEntry } from "./build";

const DEFAULT_API_BASE = "https://app.clawso.ai";
const MAX_BUNDLE_BYTES = 5 * 1024 * 1024;

export interface PublishOptions {
  /** Marketplace API base; default https://app.clawso.ai. */
  apiBase: string;
  /** Publisher bearer token. */
  token?: string;
  /** Skip the network POST; resolve and print the multipart plan instead. */
  dryRun: boolean;
}

export interface MultipartPlan {
  apiBase: string;
  endpoint: string;
  skin: { id: string; version: string; name?: string };
  bundle: { filename: string; bytes: number; sha256: string };
  adminReviewChecklist: { filename: string; bytes: number; source: "file" | "generated" };
  deploymentVerification: { filename: string; bytes: number; source: "file" | "generated" };
  releaseNotes: { present: boolean; bytes: number };
}

function sha256Hex(buf: Buffer): string {
  return crypto.createHash("sha256").update(buf).digest("hex");
}

/** Comma-list of the non-`default` mode names declared in the manifest. */
function declaredModes(manifest: Record<string, any>): string[] {
  const modes = manifest?.modes && typeof manifest.modes === "object" ? manifest.modes : {};
  return Object.keys(modes).filter((m) => m !== "default");
}

/**
 * Default admin-review checklist for a declarative skin. Generated only when the
 * author hasn't supplied admin_review_checklist.md, so review still has a
 * baseline statement of what the bundle is and the guarantees the kit enforces.
 */
export function defaultAdminReviewChecklist(manifest: Record<string, any>): string {
  const id = String(manifest.id ?? "");
  const version = String(manifest.version ?? "");
  const contract = String(manifest.contract ?? "");
  const modes = declaredModes(manifest);
  const hasStyles = typeof manifest.styles === "string" && manifest.styles.length > 0;
  return [
    `# Admin Review Checklist — ${manifest.name ?? id} ${version}`,
    "",
    "This is a **declarative Clawso skin**. It carries no executable code.",
    "",
    `- [x] Contract version: \`${contract || "unknown"}\``,
    `- [x] Modes: ${modes.length ? modes.map((m) => `\`${m}\``).join(", ") : "_(none declared)_"}`,
    `- [x] No JavaScript — appearance is CSS variables + scoped CSS only`,
    `- [x] Assets are bundled (no off-bundle \`url()\`, no \`@import\`, no remote fetch)`,
    `- [x] No \`<script>\`, \`javascript:\`, or \`expression()\` constructs in skin.css`,
    `- [x] Does not hide or cover protected shell anchors (topbar, buttons, modals)`,
    hasStyles
      ? `- [x] skin.css scoped to published \`data-region\` / \`data-part\` anchors`
      : `- [x] Token-only skin (no skin.css)`,
    `- [x] Passed \`clawso-skin validate\` (schema + security) before submission`,
    "",
    "_Generated by `clawso-skin publish`; edit `admin_review_checklist.md` in the skin",
    "directory to supply your own._",
    "",
  ].join("\n");
}

/**
 * Default deployment-verification notes for a declarative skin: the concrete
 * steps a reviewer (or the author) follows to confirm the skin renders.
 */
export function defaultDeploymentVerification(manifest: Record<string, any>): string {
  const id = String(manifest.id ?? "");
  const modes = declaredModes(manifest);
  const modeFlags = modes.length
    ? modes.map((m) => `\`clawso-skin preview <dir> --mode ${m}\``).join("\n  - ")
    : "`clawso-skin preview <dir>`";
  return [
    `# Deployment Verification — ${manifest.name ?? id}`,
    "",
    "Steps to confirm the skin applies cleanly against the current shell snapshot:",
    "",
    `1. \`clawso-skin validate <dir>\` — all schema + security rules PASS.`,
    `2. \`clawso-skin build <dir>\` — produces \`${id}.skin\` without error.`,
    `3. Preview each declared mode and confirm tokens + CSS render:`,
    `  - ${modeFlags}`,
    `4. After install, open **Settings → Appearance** and select this skin; confirm`,
    `   the picker shows it and switching modes recolors the shell.`,
    "",
    "_Generated by `clawso-skin publish`; edit `deployment_verification.md` in the",
    "skin directory to supply your own._",
    "",
  ].join("\n");
}

/** Read a publish-meta markdown file from the skin dir, or generate a default. */
function resolveMarkdown(
  dir: string,
  filename: string,
  generate: () => string
): { content: string; source: "file" | "generated" } {
  const p = path.join(dir, filename);
  if (fs.existsSync(p) && fs.statSync(p).isFile()) {
    return { content: fs.readFileSync(p, "utf8"), source: "file" };
  }
  return { content: generate(), source: "generated" };
}

export interface PublishResult {
  /** The resolved multipart plan (always produced, dry-run or not). */
  plan: MultipartPlan;
  /** The parsed submit response, present only on a real (non-dry-run) POST. */
  response?: Record<string, any>;
  /** Resolved bundle bytes + the markdown bodies (so the CLI can report/post). */
  bundleBytes: Buffer;
  checklistMd: string;
  verificationMd: string;
  releaseNotes?: string;
}

/**
 * Validate, build the tarball, resolve the two markdown bodies, and (unless
 * dry-run) POST to the marketplace. Throws on validation failure, missing token,
 * oversized bundle, or a non-2xx response.
 */
export async function publishSkin(
  dir: string,
  opts: PublishOptions,
  releaseNotes?: string
): Promise<PublishResult> {
  // 1. Validate (schema + security). Abort before building anything.
  const validation = validateSkin(dir);
  if (!validation.ok || !validation.manifest) {
    const failed = validation.results.filter((r) => !r.pass).map((r) => r.rule);
    throw new Error(
      `validation failed (${failed.join(", ") || "manifest unreadable"}); run \`clawso-skin validate ${dir}\``
    );
  }
  const manifest = validation.manifest;
  const id = String(manifest.id ?? "");
  const version = String(manifest.version ?? "");
  if (!id) throw new Error("skin.json has no id; cannot publish");
  if (!version) throw new Error("skin.json has no version; cannot publish");

  // 2. Build the .skin tar.gz in memory.
  const { bytes: bundleBytes } = buildSkinTarball(dir);
  if (bundleBytes.length > MAX_BUNDLE_BYTES) {
    throw new Error(
      `bundle is ${bundleBytes.length} bytes, exceeding the ${MAX_BUNDLE_BYTES}-byte (5MB) submit limit`
    );
  }
  const bundleSha = sha256Hex(bundleBytes);

  // 3. Resolve the two review markdown files (author-provided or generated).
  const checklist = resolveMarkdown(dir, "admin_review_checklist.md", () =>
    defaultAdminReviewChecklist(manifest)
  );
  const verification = resolveMarkdown(dir, "deployment_verification.md", () =>
    defaultDeploymentVerification(manifest)
  );
  const checklistBytes = Buffer.byteLength(checklist.content, "utf8");
  const verificationBytes = Buffer.byteLength(verification.content, "utf8");
  const notes = typeof releaseNotes === "string" && releaseNotes.length > 0 ? releaseNotes : undefined;

  const endpoint = `${opts.apiBase.replace(/\/+$/, "")}/api/marketplace/skins/submit`;
  const plan: MultipartPlan = {
    apiBase: opts.apiBase,
    endpoint,
    skin: { id, version, name: manifest.name ? String(manifest.name) : undefined },
    bundle: { filename: `${id}.skin`, bytes: bundleBytes.length, sha256: bundleSha },
    adminReviewChecklist: {
      filename: "admin_review_checklist.md",
      bytes: checklistBytes,
      source: checklist.source,
    },
    deploymentVerification: {
      filename: "deployment_verification.md",
      bytes: verificationBytes,
      source: verification.source,
    },
    releaseNotes: { present: Boolean(notes), bytes: notes ? Buffer.byteLength(notes, "utf8") : 0 },
  };

  const result: PublishResult = {
    plan,
    bundleBytes,
    checklistMd: checklist.content,
    verificationMd: verification.content,
    releaseNotes: notes,
  };

  // 4. Dry-run: stop before touching the network.
  if (opts.dryRun) return result;

  // 5. Real run: token is mandatory, then POST multipart.
  if (!opts.token) {
    throw new Error(
      "no publisher token: pass --token <t> or set CLAWSO_DEV_TOKEN (a dealer/publisher dev token)"
    );
  }

  const form = new FormData();
  form.append(
    "bundle",
    new Blob([bundleBytes], { type: "application/gzip" }),
    `${id}.skin`
  );
  form.append(
    "admin_review_checklist",
    new Blob([checklist.content], { type: "text/markdown" }),
    "admin_review_checklist.md"
  );
  form.append(
    "deployment_verification",
    new Blob([verification.content], { type: "text/markdown" }),
    "deployment_verification.md"
  );
  if (notes) form.append("release_notes", notes);

  let res: Response;
  try {
    res = await fetch(endpoint, {
      method: "POST",
      headers: { Authorization: `Bearer ${opts.token}` },
      body: form,
    });
  } catch (e) {
    throw new Error(`request to ${endpoint} failed: ${(e as Error).message}`);
  }

  const text = await res.text();
  let body: Record<string, any>;
  try {
    body = text ? JSON.parse(text) : {};
  } catch {
    throw new Error(`submit returned ${res.status} with non-JSON body: ${text.slice(0, 500)}`);
  }
  if (!res.ok) {
    const msg = body?.message || body?.error || `HTTP ${res.status}`;
    const extra = body?.field_errors
      ? `\n  field errors: ${JSON.stringify(body.field_errors)}`
      : body?.violations
        ? `\n  violations: ${JSON.stringify(body.violations)}`
        : body?.missing
          ? `\n  missing: ${JSON.stringify(body.missing)}`
          : "";
    throw new Error(`submit failed (${res.status}): ${msg}${extra}`);
  }

  result.response = body;
  return result;
}

/** A flat, printable summary of the entries in the built bundle. */
export function describeEntries(entries: BundleEntry[]): string[] {
  return entries.map((e) => `${e.name} (${e.data.length} bytes)`);
}
